### ISSUE TITLE
calibrate temperature measurement endpoint

### ISSUE THREAD

**Issue by tobit6795** [marcelrv/nefit_easy_protocol#1]
it is possible to calibrate the temperature sensor via the busch/junkers android application, but i couldnt find any endpoint here

**Comment by marcelrv** [comment]
This endpoint I believe is linked to the 'calibration' option in the app.

https://github.com/marcelrv/nefit_easy_protocol/blob/master/hc1-temperatureAdjustment.md

**Comment by tobit6795** [comment]
will try out, thank you !
